runtime: java
env: flex
runtime_config:
  jdk: openjdk8

resources:
  cpu: 1
  memory_gb: 6
  disk_size_gb: 10

env_variables:
  SPRING_PROFILES_ACTIVE: "gcp,postgresql"
  #CLOUD_SDK_HOME: C:\Users\manue\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin
  #GOOGLE_APPLICATION_CREDENTIALS: C:\Program Files\GOOGLE_AuthenticationKey\gameet-03042022-2e2e09915b08.json

handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1

#entrypoint: src/main/java/com/salesianostriana/gameetapi/GameetApiApplication.java